// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type EventsStreamGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/events_controller.ts').default['stream'], false>
}
type EventsRecentemailsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/events_controller.ts').default['getRecentEmails'], false>
}
type MailSendPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/mail_controller.ts').default['send'], false>
}
type WebhooksInboundemailPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/webhooks_controller.ts').default['inboundEmail'], false>
}
export interface ApiDefinition {
  'events': {
    'stream': {
      '$url': {
      };
      '$get': EventsStreamGetHead;
      '$head': EventsStreamGetHead;
    };
    'recent-emails': {
      '$url': {
      };
      '$get': EventsRecentemailsGetHead;
      '$head': EventsRecentemailsGetHead;
    };
  };
  'mail': {
    'send': {
      '$url': {
      };
      '$post': MailSendPost;
    };
  };
  'webhooks': {
    'inbound-email': {
      '$url': {
      };
      '$post': WebhooksInboundemailPost;
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
